import { Inter } from "next/font/google";
import "../styles/globals.css";
import Head from "next/head";
import { Providers } from "@/lib/providerStore";
import { ClerkProvider } from "@clerk/nextjs";
import { Metadata } from "next";

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Maxway",
  description: "Maxway - fast delivery, comfort zone!",
  icons: {
    icon: ["/favico.ico"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <Head>
          <meta name="description" content="Generated by create next app" />
          <link
            rel="icon"
            href="/icon?<generated>"
            type="image/<generated>"
            sizes="<generated>"
          />
          <script
            dangerouslySetInnerHTML={{
              __html: `
              (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
              m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
              (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

              ym(97216045, "init", {
                clickmap:true,
                trackLinks:true,
                accurateTrackBounce:true,
                webvisor:true
              });
            `,
            }}
          />
        </Head>
        <body className={`${inter.className}`}>
          <Providers>{children}</Providers>
          <noscript>
            <div>
              <img
                src="https://mc.yandex.ru/watch/97216045"
                style={{ position: "absolute", left: "-9999px" }}
                alt="yandex metrics"
              />
            </div>
          </noscript>
        </body>
      </html>
    </ClerkProvider>
  );
}
