import { Inter } from "next/font/google";
import "../styles/globals.css";
import Head from "next/head";
import { Providers } from "@/lib/providerStore";
import YandexMetrika from "@/components/Metrics/Head";
// import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <ClerkProvider>
    <html lang="en">
      <Head>
        <YandexMetrika />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body className={`${inter.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
    // {/* </ClerkProvider> */}
  );
}
